FROM node:20

# Create app directory
WORKDIR /frontend

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the project
COPY . .

# Expose Vite dev server port
EXPOSE 5173

# Start Vite
CMD ["npm", "run", "dev", "--", "--host"]
