FROM node:20

# Create app directory
WORKDIR /front/src

# Install dependencies first (better caching)
COPY package*.json ./
RUN npm install

# Copy project files
COPY /src .

# Expose Vite dev server port
EXPOSE 5173

# Default command
CMD ["npm", "run", "dev"]